s=set()
n=int(input("enter no1:"))
s.add(n)
n=int(input("enter no2:"))
s.add(n)
n=int(input("enter no3:"))
s.add(n)
n=int(input("enter no4:"))
s.add(n)
n=int(input("enter no5:"))
s.add(n)
n=int(input("enter no6:"))
s.add(n)
n=int(input("enter no7:"))
s.add(n)
n=int(input("enter no8:"))
s.add(n)
print(s,type(s))